version: '3.9'
services:
  db:
    image: postgres
    restart: always
    ports:
      - '5432:5432'
    shm_size: 128mb
    environment:
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_PASSWORD: ${DATABASE_PASS}
      POSTGRES_DB: ${DATABASE_NAME}
    container_name: realStateSystem
    volumes:
      - './postgres:/var/lib/postgresql/data'